name: Build Client-377

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Release, Debug]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure with CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build with CMake
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-377-${{ matrix.build_type }}
          path: |
            build/**/*.dll
            build/**/*.pdb
            build/**/*.lib
            src/client_377.h
